---
# Source: nginx/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: kikitrade-dev-nginx
  labels:
    app.kubernetes.io/name: nginx
    helm.sh/chart: nginx-9.5.18
    app.kubernetes.io/instance: kikitrade-dev-nginx
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: kikitrade-dev-nginx
